name: Build and Release Amsterdam Assets
on:
  release:
    types: [published]
jobs:
  build-and-upload:
    runs-on: host
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
      - name: Build Binaries
        run: |
          # Build targets: Linux AMD64, Linux ARM64 (RPi), Windows AMD64, macOS ARM64 (Apple Silicon), macOS AMD64 (Intel)
          GOOS=linux GOARCH=amd64 go build -o amsterdam-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o amsterdam-linux-arm64
          GOOS=windows GOARCH=amd64 go build -o amsterdam-windows-amd64.exe
          GOOS=darwin GOARCH=arm64 go build -o amsterdam-macos-arm64
          GOOS=darwin GOARCH=amd64 go build -o amsterdam-macos-amd64
      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            amsterdam-linux-amd64
            amsterdam-linux-arm64
            amsterdam-windows-amd64.exe
            amsterdam-macos-arm64
            amsterdam-macos-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
