#
# Amsterdam Web Communities System
# Copyright (c) 2025 Erbosoft Metaverse Design Solutions, All Rights Reserved
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
site:
  baseURL: "http://localhost:1323"
  title: "Amsterdam Web Communities System"
  topRefresh: 300
  loginCookieName: AmsterdamAuth
  loginCookieAge: 365
  sessionExpire: "3h"
  userAgreementResource: "useragreement.html"
  policyResource: "policy.html"
database:
  driver: "mysql"
  dsn: "amsdb:x00yes2k@tcp(localhost)/amsterdam?parseTime=true&loc=UTC"
defaults:
  language: "en-US"
  timezone: "America/Denver"
email:
  host: localhost
  port: 1025
  tls: none
  authType: none
  user: jrn
  password: foobiebletch
  mailFromAddr: "nobody@example.com"
  mailFromName: "Amsterdam E-Mail Service"
  signature: |-
    Amsterdam - community services, conferencing and more.  <http://git.erbosoft.com/amy/amsterdam>
  disclaimer: |-
    Message sent via Amsterdam Web Communities System - <http://git.erbosoft.com/amy/amsterdam>
    The Amsterdam Project is not responsible for the contents of this message
    Report abuses to: <abuse@example.com>
rendering:
  cookiekey: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  countryList:
    prioritize: US
  veniceCompatibleImageURLs: false
resources:
  viewTemplateDir: ""
  externalContentPath: ""
  externalResourcePath: ""
posting:
  externalDictionary: ""
  uploads:
    maxSize: "1M"
    noCompressTypes:
      - "image/gif"
      - "image/jpg"
      - "image/jpeg"
      - "image/png"
tuning:
  workerTasks: 4
  queues:
    auditWrites: 16
    contextRecycle: 16
    emailRecycle: 16
    emailSend: 16
    ipBans: 32
    workerTasks: 128
  caches:
    ads: 30
    communities: 50
    communityProps: 100
    conferences: 100
    conferenceProps: 100
    contactInfo: 100
    members: 250
    menus: 100
    services: 50
    users: 100
    userProps: 100