#
# Amsterdam Web Communities System
# Copyright (c) 2025 Erbosoft Metaverse Design Solutions, All Rights Reserved
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
site:
  title: "Amsterdam Web Communities System"
  topRefresh: 300
  userAgreement:
    title: "Amsterdam User Agreement"
    text: >
      Text of this agreement is TBD.
database:
  driver: "mysql"
  dsn: "amsdb:x00yes2k@tcp(localhost)/amsterdam?parseTime=true&loc=Local"
email:
  host: smtp.example.com
  port: 587
  tls: starttls
  authType: plain
  user: jrn
  password: foobiebletch
rendering:
  templatedir: custom_templates
  cookiekey: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
